version: "3"
services:
  authors-service:
    image: pjcaiza/app-authors:1.0.0
    ports:
      - 9090:9090
    environment:
      - SERVER_PORT=9090
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres-sql
      - DB_DRIVER=pg
      - DB_DATABASE=distribuida
      - DB_PORT=5432
    depends_on:
      postgres-sql:
        condition: service_healthy
  postgres-sql:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: distribuida
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 10s
      retries: 10




